import { Experience as experienceTypes } from "@/lib/types";

export const experience: experienceTypes[] = [
  {
    title: "Frontend Engineer",
    company: "Nord Finance(Kohin)",
    tip: "Web3 betting insurance provider",
    startDate: "May 2024",
    endDate: "Present",
    location: "Remote, India",
    description: [
      `Developed the Kohin frontend using Next.js, Tailwind CSS, and React Query, wagmi, appkit to list all the bets placed on any platforms.`,
      `Used Context API and React Query for efficient state management, improving performance and data synchronization. Added Wagmi contract interaction for performing transaction.`,
      `Leveraged Next.js server-side capabilities to securely handle API calls, preventing exposure in the network tab.`,
      `Developed an interactive Admin dashboard using Next.js, Tailwind CSS, and React Query, React table to visualize real-time data insights`,
    ],
    lang: [
      "Javascript",
      "Typescript",
      "Nodejs",
      "Figma",
      "Wagmi",
      "Viem",
      "Next.js",
      "React Query",
      "React Table",
      "Reown Apkit",
      "React Chart.",
    ],
  },
  {
    title: "Frontend Engineer",
    company: "Nord Finance(ReputeX)",
    tip: "The Modular Reputation Layer",
    startDate: "May 2024",
    endDate: "Present",
    location: "Remote, India",
    description: [
      `Implemented front-end app using Next.js, Context API, React Query and Tailwind CSS.`,
      `Implemented PWA for the front-end Next.js application, enabling web-app usage on mobile.`,
      `Optimized the speed of the Next.js app up to 80%`,
    ],
    lang: [
      "Javascript",
      "Typescript",
      "Nodejs",
      "Figma",
      "NextJs",
      "Typescript",
      "Wagmi",
      "Viem",
      "Reown Apkit",
    ],
  },
];
